buildscript {
  repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
  }

  dependencies {
    classpath libs.gradle
    classpath libs.kotlin.gradle.plugin
  }
}

apply plugin: 'com.android.application'

android {
  namespace 'com.michatec.store'
  compileSdk 36

  defaultConfig {
    applicationId 'com.michatec.store'
    minSdk 30
    targetSdk 36
    versionCode 17
    versionName '1.7'

    def languages = [ 'en' ]
    buildConfigField 'String[]', 'LANGUAGES', '{ "' + languages.join('", "') + '" }'
    resConfigs languages
  }

  buildFeatures {
    buildConfig = true
  }

  sourceSets {
    main {
        java.srcDirs += 'src/main/kotlin'
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  flavorDimensions "distributor"
  productFlavors {
    michas {
      dimension "distributor"
      buildConfigField "boolean", "FLAVOR_FDROID", "false"
    }
    fdroid {
      dimension "distributor"
      buildConfigField "boolean", "FLAVOR_FDROID", "true"
    }
  }

  buildTypes {
    debug {
      minifyEnabled false
      shrinkResources false
    }
    release {
      minifyEnabled true
      shrinkResources false
    }
  }

  def keystorePropertiesFile = rootProject.file('keystore.properties')
  if (keystorePropertiesFile.exists()) {
    def keystoreProperties = new Properties()
    keystoreProperties.load(keystorePropertiesFile.newDataInputStream())

    def signing = [
      storeFile: keystoreProperties['store.file'],
      storePassword: keystoreProperties['store.password'],
      keyAlias: keystoreProperties['key.alias'],
      keyPassword: keystoreProperties['key.password']
    ]

    if (!signing.any { _, v -> v == null }) {
      signingConfigs {
        primary {
          storeFile file(signing.storeFile)
          storePassword signing.storePassword
          keyAlias signing.keyAlias
          keyPassword signing.keyPassword
          enableV2Signing false
        }
      }
    }
  }
}

repositories {
  google()
  mavenCentral()
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation libs.kotlin.stdlib
  implementation libs.fragment.ktx
  implementation libs.viewpager2
  implementation libs.vectordrawable
  implementation libs.okhttp
  implementation libs.rxjava
  implementation libs.rxandroid
  implementation libs.jackson.core
  implementation libs.picasso
  implementation libs.freedroidwarn
}
